name: CI/CD

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Version ${{ github.ref }}
          draft: false
          prerelease: false

  build:
    name: Test and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node & npm
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: yarn install

      # - name: Test
      #   run: yarn test

      - name: Build
        run: yarn build

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: "**/dist"
          key: build-artifacts-${{ github.sha }}

  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: build

    env:
      NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore build artifacts
        uses: actions/cache@v3
        with:
          path: "**/dist"
          key: build-artifacts-${{ github.sha }}

      - name: Setup node & npm
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Publish to NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set "//registry.npmjs.org/:_authToken" "${NPM_TOKEN}"
          npm -r publish ./dist --access=public --no-git-checks
