name: CI/CD

on:
  release:
    types: [created,edited]
  workflow_dispatch:

jobs:
  build:
    name: Build, lint, test and publish

    runs-on: ubuntu-latest

    env:
      NODE_ENV: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node & npm
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          architecture: 'x64'
          registry-url: https://registry.npmjs.org/

      - run: yarn install

      # - name: Test
      #   run: yarn test

      - name: Build
        run: yarn build

      - name: Publish to NPM
        run: npm publish dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
